config/routes.rb
Rails.application.routes.draw do

  root to: 'links#index'
  resources :links do 
    member do 
      get :flip_status
    end
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/link.rb
require 'uri'

class Link < ActiveRecord::Base
	validates :url, :format => URI::regexp(%w(http https))
	validates :title, presence: true
	belongs_to :user

	def read_status_name
		read ? "Mark as Read" : "Mark as Unread"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :links
  
  validates :password, length: { minimum: 8 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_filter :authorize

	def index	
		@links = @current_user.links
	end

	def new
	end

	def create
		link = Link.new(link_params)
		if link.save
			redirect_to links_path
			flash[:notice] = "You added a link!"
		else
			flash.now[:error] = "Could not save link"
    end
	end

	def show
		@link = Link.find(params[:id])
	end

	def flip_status
    link = Link.find(params[:id])
    link.read = !link.read
    link.save

    redirect_to link_path(link)
  end

	private

	def link_params
		params.require(:link).permit(:title, :url, :user_id)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 def new
 end

 def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
	end

	 def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughtbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>


<%= yield %>

</body>
</html>

app/views/links/_new_link.html.erb
<h4>Add a link </h4>

<%= form_for :link, url: root_path do |f| %>

  Title: <%= f.text_field :title %>
  URL: <%= f.text_field :url %>
  <%= f.submit "Submit" %>

<% end %>

app/views/links/index.html.erb
<h1>Box of Thoughts</h1>
<%= render 'new_link' %>

<% @current_user.links.each do |link| %>
	<%= link.title %>
	<%= link.url %>
	<%= link_to(link.read_status_name, flip_status_link_path(link)) %>
<% end %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>